
#spring.application.name=proofchain

spring.datasource.url=jdbc:postgresql://saas-proofchain-db-instance-1.cn46c0m6qi80.sa-east-1.rds.amazonaws.com:5432/proofchain
spring.datasource.username={DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/proofchain}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}



