spring.application.name=proofchain

## criar padrão de configuração HTTPS

#server.port=8443
#server.ssl.enabled=true
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=${PASS_HTTPS}
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=springboot



spring.datasource.url=jdbc:postgresql://localhost:5432/proofchain
spring.datasource.username=${USER}
spring.datasource.password=${PASSWORD}

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.engine.jdbc.connections=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF