
#spring.application.name=proofchain
#
######## DEV ########
spring.datasource.url=jdbc:postgresql://localhost:5432/proofchain
spring.datasource.username=admin
spring.datasource.password=123456

######## PROD ########
#spring.datasource.url=jdbc:postgresql://saas-proofchain-db-instance-1.cn46c0m6qi80.sa-east-1.rds.amazonaws.com:5432/proofchain
#spring.datasource.username={DB_USER}
#spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.engine.jdbc.connections=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF