spring.datasource.url=jdbc:postgresql://localhost:5432/proofchain
spring.datasource.username=admin
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=none
spring.datasource.driver-class-name=org.postgresql.Driver

