import { motion, AnimatePresence } from "framer-motion";
import { QrCode, ShieldCheck, Calendar, Clock, Hash, Building2, Download, X } from "lucide-react";
import { useStore } from "@/store/useStore";

export const CertificatePreviewModal = () => {
  const { proofModal, setProofModal, proofData } = useStore();
  if (!proofData) return null;
  const { certificate, proof } = proofData;
  return (<AnimatePresence>{proofModal && <div className="fixed inset-0 bg-dark/80 backdrop-blur-sm flex items-center justify-center z-50 p-4"><motion.div initial={{ scale: 0.9, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} exit={{ scale: 0.9, opacity: 0 }} className="bg-white rounded-2xl w-full max-w-4xl overflow-hidden shadow-2xl"><div className="bg-gradient-to-r from-primary to-accent p-6 text-white flex justify-between items-center"><div className="flex items-center gap-3"><ShieldCheck size={28}/><h2 className="text-2xl font-bold">Certificado Digital</h2></div><button onClick={() => setProofModal(false)} className="p-2 hover:bg-white/20 rounded-xl"><X size={20}/></button></div><div className="p-8 space-y-8"><div className="text-center space-y-3"><p className="text-gray-500 uppercase tracking-widest text-sm font-semibold">Certificamos que</p><h1 className="text-4xl md:text-5xl font-bold text-dark tracking-tight">{certificate.name}</h1><p className="text-lg text-gray-600">concluiu com êxito o curso</p><h3 className="text-2xl font-semibold text-primary">{certificate.course}</h3><div className="flex flex-wrap justify-center gap-6 mt-4 text-sm text-gray-600"><span className="flex items-center gap-2"><Calendar size={16}/>{certificate.date}</span><span className="flex items-center gap-2"><Clock size={16}/>{certificate.loadHours} horas</span><span className="flex items-center gap-2"><Building2 size={16}/>{certificate.institution}</span></div></div><div className="bg-gray-50 rounded-xl p-6 grid md:grid-cols-2 gap-6 border border-gray-100"><div className="space-y-3"><h4 className="font-semibold text-dark flex items-center gap-2"><Hash size={16}/>Registro Criptográfico</h4><code className="block bg-white px-3 py-2 rounded-lg text-xs font-mono break-all border border-gray-200">{proof.hash}</code><code className="block bg-white px-3 py-2 rounded-lg text-xs font-mono break-all border border-gray-200">{proof.txHash}</code></div><div className="flex flex-col items-center justify-center space-y-3"><div className="w-28 h-28 bg-white border-2 border-gray-200 rounded-xl flex items-center justify-center"><QrCode size={56} className="text-dark"/></div><p className="text-xs text-gray-500 text-center">Escaneie para validar publicamente</p></div></div><div className="flex justify-between items-center text-sm text-gray-500 pt-4 border-t"><span>Assinado digitalmente por <strong>{certificate.institution}</strong></span><span>Registrado em: {new Date(proof.timestamp).toLocaleString()}</span></div></div></motion.div></div>}</AnimatePresence>);
};