# Redireciona o cliente do Spring AI para a infraestrutura do Groq
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.api-key=COLE_AQUI_A_SUA_CHAVE_DO_GROQ

# Escolha o modelo gratuito e de altíssima velocidade do Groq
spring.ai.openai.chat.options.model=llama3-8b-8192
spring.ai.openai.chat.options.temperature=0.2


#spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.options.model=qwen2.5:1.5b
#spring.ai.ollama.stream=false
#spring.ai.ollama.chat.options.temperature=0.2